{% set name = "schema" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b536f2375b49fdf56f36279addae98bd86a8afbd58b3c32ce363c464bed5fc1c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - contextlib2 ==0.5.5

test:
  imports:
    - schema

about:
  home: https://github.com/keleshev/schema
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Schema validation just got Pythonic

  description: |
    schema is a Python library for validating data structures, such as those
    obtained from config-files, forms, external services or command-line
    parsing, converted from JSON/YAML (or something else) to Python data-types.
  dev_url: https://github.com/keleshev/schema

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
    - MaxRis
