travis:
  secure:
    BINSTAR_TOKEN: b4vkUV6O/Kic1VfcMOzIF5rkWf551TSYaS1t/CgDqq35RngIVWgF+1yZAhvmZaVDCay12XFFBdFQ9xNkhtYhOACogI3GiKAmSr+EzH5N0ZgWB9GQr1yx7ErgSoOPIjewOS0f/WW1ldoqUomuE2+nkL8WEVnS4lbt4SBBtg6qQ+Nw/6WV+N2O+5AcI0CThGm8Re+OhPhXl3IrlnxFsApR8nrIkq7D7zDps9rwPlJTto8NKSYzY8+gFoFK4PUoCx9bdCQ/jvNiJPRLA8WEmTW1j68T6GIF2kQMmekvKrLKaxlJDkWqMsdUwao0VQwFzg4t4tK3Mce3S6kwz5/7dvknCtLJ6iZpjdGxeK47BNmaajwhQnJLVT2+40xJdr2X6YH3tLGF+J+HUNPFpEP/tM0q6fjf/MxMKWRClej8kWLdbJx+jqme1rx1NjyTxgWptEMe2MFS22eo/ee1E78ufJ6Z69Mv/Bmj9hNxTytoLIPm1aWgyM/dpLQwgLYEBC4sIlhtJ3Pf6/UPUCo4qS85yJWiFdm2rHwYJtaUAf6tuI8NF7k+mT1273oHsGRYqDgwgi84BK3JQgfRYqBErxaBGvqr6HYl+JmbiBLKrMxetyRwpP2zQx0kCKokrXA0MYNHBzyrxF0XxOfcxF+ott0BVe457ach0u4AxRQwWAr2MMlL1wo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
